// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusSystem.Entities;

[Table("Route")]
public partial class Route
{
    [Key]
    public int RouteID { get; set; }

    [Required(ErrorMessage = "Route Number is Required.")]
    [StringLength(10, ErrorMessage = "Route Number is a maximum of 10 characters.")]
    public string RouteNumber { get; set; }

    [Required(ErrorMessage = "Bus Number is Required.")]
    [StringLength(10, ErrorMessage = "Bus Number is a maximum of 10 characters.")]
    public string BusNumber { get; set; }

    [Range(1, int.MaxValue, ErrorMessage = "Capacity must be greater than 0.")]
    public int Capacity { get; set; }

    [Column(TypeName = "decimal(3, 0)")]
    [Range(0.00, double.MaxValue, ErrorMessage = "Fare must not be negative.")]
    public decimal Fare { get; set; }
}