// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WestWindSystem.Entities
{
    public partial class Orders_GetByShipperResult
    {
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public int? SalesRepID { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [StringLength(40)]
        public string ShipName { get; set; }
        public int? ShipAddressID { get; set; }
        [StringLength(250)]
        public string Comments { get; set; }
    }
}
