// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BusSystem.Entities;
using Microsoft.EntityFrameworkCore;

namespace BusSystem.DAL;

public partial class BusDataContext : DbContext
{
    public BusDataContext(DbContextOptions<BusDataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Route> Routes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Route>(entity =>
        {
            entity.Property(e => e.BusNumber).IsFixedLength();
            entity.Property(e => e.RouteNumber).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}