// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WestWindSystem.Entities;

namespace WestWindSystem.DAL
{
    public partial interface IWestWindContextProcedures
    {
        Task<List<Customers_GetByPartialCompanyNameResult>> Customers_GetByPartialCompanyNameAsync(string partialName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Customers_GetByPartialContactNameResult>> Customers_GetByPartialContactNameAsync(string partialName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Orders_GetByCustomerResult>> Orders_GetByCustomerAsync(string customerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Orders_GetByEmployeeResult>> Orders_GetByEmployeeAsync(int? employeeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Orders_GetByShipperResult>> Orders_GetByShipperAsync(int? shipVia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Products_GetByPartialProductNameResult>> Products_GetByPartialProductNameAsync(string partialName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Products_GetByPriceRangeResult>> Products_GetByPriceRangeAsync(decimal? minPrice, decimal? maxPrice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Products_GetBySupplierResult>> Products_GetBySupplierAsync(int? supplierID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Suppliers_GetByPartialCompanyNameResult>> Suppliers_GetByPartialCompanyNameAsync(string partialName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Suppliers_GetByPartialContactNameResult>> Suppliers_GetByPartialContactNameAsync(string partialName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
